### ISSUE TITLE
Follow and like likers of a post

### ISSUE THREAD

**Issue by virginsince1997** [pauloromeira/onegram#1]
Hello dev nice work, is it possible to like and follow likers of a. Particular page

**Comment by pauloromeira** [comment]
Hello. Thanks.

Sure. A post is identified by its shortcode: `https://www.instagram.com/p/{shortcode}`

To follow who liked the post, and then like his last post, you just need to write a simple script:
```py
from onegram import likes, posts
from onegram import like, follow

for liker in likes('{shortcode}'):
   follow(liker)
   liker_post = next(posts(liker))
   like(liker_post)
```
