### ISSUE TITLE
DOCUMENTATION AND OTHER ISSUES

### ISSUE THREAD

**Issue by virginsince1997** [pauloromeira/onegram#2]
Please can you show me an example on how to use queries or a documentation  quite confusing
,,,
user_info 
followers 
following
posts
post_info
likes 
comments
feed
explore
,,,

and for some reason action.likes dont work for me .

`login(username='xxxxxxx', password='xxxxxxx')
for liker in likes('BhT6gpHFwMj'):
            like(liker)
`

![capture](https://user-images.githubusercontent.com/21218962/38490008-d0d6aad0-3bdf-11e8-8ce8-5de60236b1d0.PNG)

thanks

**Comment by pauloromeira** [comment]
Hello. Sorry about the documentation. I can't work on it right now, maybe soon. For now, I would suggest you to play a bit with onegram using [ipython](https://github.com/ipython/ipython). All responses are python dicts.

About `action.likes`: on instagram you can't like a person, but you can follow instead. The only thing you can like is a post.

You can try to change your code a bit:
```py
from onegram import likes, like, posts

for liker in likes('BhT6gpHFwMj'): 
    # Like last post of the liker - if it has any
    last_post = next(posts(liker), None)
    if last_post:
        like(last_post)
```

Don't forget to keep it updated: `pip install -U onegram`.

**Comment by pauloromeira** [comment]
I'm closing this issue, but feel free to keep in touch. Later I'll open docs-related issues. 

If you prefer, there's a also [chat room](https://gitter.im/pauloromeira/onegram) where you can place any question.
