### ISSUE TITLE
Searching posts by tag

### ISSUE THREAD

**Issue by lormayna** [pauloromeira/onegram#3]
Hi Paulo,
is there a way to search posts by tag?

**Comment by pauloromeira** [comment]
Hello, Iormayna

Not yet. But maybe soon!

**Comment by lormayna** [comment]
Could you provide some hints how to implement? Maybe I can work on it :)

Il sab 28 apr 2018, 21:22 Paulo Romeira <notifications@github.com> ha
scritto:

**Comment by pauloromeira** [comment]
Hello!

I've just solve the issue. You can check this commit to see how: 2be3b774ad19bcded9e8b7fc035724cab7059cbd
